### PR TITLE
fix: image placeholder in backend

### PR DESCRIPTION
**Pull request by maryamreis**
# Description

Image placeholder updated in backend

### CODE REVIEW

**Comment by vanessa-cooper** [comment]
On it! I'll review the changes as soon as possible!

**Review by vanessa-cooper — CHANGES_REQUESTED** [review]
I don’t think it’ll work. Make sure it passes all checks, and  only then you’ll be able to merge the PR.

**Comment by maryamreis** [comment]
Screenshot 2022-09-23 at 20 34 19

**Review by vanessa-cooper — APPROVED** [review]
Perfect Maryam! You're now able to merge the PR.

**Pull request merged**
